---
abstract: 'Module for creating Perl SADI services'
author:
  - 'Ben Vandervalk (ben [dot] vvalk [at] gmail [dot] com), Edward Kawas, Martin Senger'
build_requires:
  File::Slurp: 0
  IO::String: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300005, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SADI-Simple
requires:
  HTTP::Date: 0
  Log::Log4perl: 0
  RDF::Trine: 0.135
  Template: 0
  URI: 0
version: 0.008
